import Head from 'next/head';
import Search from '@/components/Search/Search';
import MoviesList from '@/components/MoviesList/MoviesList';
import AddMovie from '@/components/AddMovie/AddMovie';
import DataProvider from '@/Providers/DataProvider';
import {ApolloProvider} from '@apollo/client';
import { client } from '@/Req/Req';

export default function Home() {
  return (
    <ApolloProvider client={client}>
      <DataProvider>
        <Head>
          <title>Movies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Search />
          <MoviesList />
          <AddMovie />
        </main>
      </DataProvider>
    </ApolloProvider>
  );
}
