import Head from 'next/head';
import {useState, useEffect} from 'react';

import Search from '@/components/Search/Search';
import MoviesList from '@/components/MoviesList/MoviesList';
import axios from 'axios';
import {MovieBaseType} from '@/Types';

export default function Home() {
  const [searchText, setSearchText] = useState('');

  const [movies, setMovies] = useState<MovieBaseType[]>([]);

  useEffect(() => {
    if (searchText.split(' ').join(''))
      axios
        .post('http://localhost:5000/graphql', {
          query:
            'query getImages($imageTitle: String){ searchMoviesByName(Title: $imageTitle) {Title Year Type Poster} }',
          variables: {imageTitle: searchText},
        })
        .then(el => setMovies(el.data.data.searchMoviesByName));

    if (!searchText)
      axios
        .post('http://localhost:5000/graphql', {
          query: '{  getMovies {Title Year Type Poster} }',
        })
        .then(el => setMovies(el.data.data.getMovies));
  }, [searchText]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Search setSearchText={setSearchText} searchText={searchText} />
        <MoviesList movies={movies} />
      </main>
    </>
  );
}
